
# jupyterbook/_config.yml
title: "Avoidable ED Visits ML Project"
author: "Bruck Adam"
logo: ""   # optional: path to logo file
execute:
  execute_notebooks: "off"

html:
  favicon: ""
  use_issues_button: false
  use_repository_button: true
  use_edit_page_button: false

repository:
  url: "https://github.com/menna1996/avoidable_ed_ml_project" 
  path_to_book: "jupyterbook"
  branch: "main"

launch_buttons:
  binderhub_url: ""
  colab_url: ""
  thebe: false
